server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      webflux:
        routes:
          - id: user-service
#            uri: lb://user-service
            uri: http://localhost:8081
            predicates:
              - Path=/user-service/**
          - id: parking-service
            uri: lb://parking-service
            predicates:
              - Path=/parking-service/**
          - id: vehicle-service
            uri: lb://vehicle-service
            predicates:
              - Path=/vehicle-service/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payment-service/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
